### ISSUE TITLE
Tracking Issue: Implement and validate the analyses based on the specification

### ISSUE THREAD

**Issue by nagisa** [near/finite-wasm#16]
This is a tracking issue for the work involving the implementation and verification of the finite-wasm WebAssembly analysis conforming to the specification in the `spec/` directory of this repository.

* [x] Implement the reference interpreter that outputs results according to the specification in an obviously correct way
    * [x] #6
* [x] #13;
    * [ ] Follow up: #14;
    * [ ] Follow up: Compare and validate the analysis results against the reference interpreter;
* [x]  #15
    * [x] Follow up: Compare and validate the analysis results against the reference interpreter;
* [x] #22
